import 'package:flutter/foundation.dart';
import '../../domain/entities/project_application_entity.dart';
import '../../domain/entities/project_partner_entity.dart';
import '../../domain/usecases/add_project_partner_usecase.dart';
import '../../domain/usecases/apply_to_project_usecase.dart';
import '../../domain/usecases/get_applications_usecase.dart';
import '../../domain/usecases/get_project_partners_usecase.dart';
import '../../domain/usecases/update_application_status_usecase.dart';

enum ProjectPartnersStatus { idle, loading, success, error }

class ProjectPartnersProvider extends ChangeNotifier {
  final GetProjectPartnersUsecase getProjectsUsecase;
  final GetFilterChipsUsecase getFilterChipsUsecase;
  final AddProjectPartnerUseCase addProjectUseCase;
  final ApplyToProjectUsecase applyToProjectUsecase;
  final GetApplicationsUsecase getApplicationsUsecase;
  final UpdateApplicationStatusUsecase updateApplicationStatusUsecase;

  ProjectPartnersProvider({
    required this.getProjectsUsecase,
    required this.getFilterChipsUsecase,
    required this.addProjectUseCase,
    required this.applyToProjectUsecase,
    required this.getApplicationsUsecase,
    required this.updateApplicationStatusUsecase,
  }) {
    _loadData();
  }

  List<String> filterChips = [];
  List<ProjectPartnerEntity> allProjects = [];

  ProjectPartnersStatus _status = ProjectPartnersStatus.idle;
  ProjectPartnersStatus get status => _status;

  String _selectedFilter = 'All Roles';
  String get selectedFilter => _selectedFilter;

  // Applications state for the currently viewed project (for creators)
  List<ProjectApplicationEntity> currentApplications = [];
  bool isLoadingApplications = false;

  Future<void> _loadData() async {
    _status = ProjectPartnersStatus.loading;
    notifyListeners();

    try {
      final chipsResult = await getFilterChipsUsecase();
      final projectsResult = await getProjectsUsecase();
      
      filterChips = chipsResult;
      allProjects = projectsResult;
      _status = ProjectPartnersStatus.success;
    } catch (e) {
      _status = ProjectPartnersStatus.error;
    }
    notifyListeners();
  }

  void setFilter(String filter) {
    _selectedFilter = filter;
    notifyListeners();
  }

  List<ProjectPartnerEntity> get filteredProjects {
    if (_selectedFilter == 'All Roles') return allProjects;
    return allProjects
        .where((p) => p.skills.any((s) => s.toLowerCase().contains(_selectedFilter.toLowerCase())))
        .toList();
  }

  Future<void> addProject(String title, String description, List<String> skills) async {
    _status = ProjectPartnersStatus.loading;
    notifyListeners();

    try {
      final project = ProjectPartnerEntity(
        id: '', // Will be generated by DB
        creatorId: '', // Handled by Supabase
        badge: 'ACADEMIC PROJECT',
        badgeColor: '#8B6F4E',
        title: title,
        description: description,
        skills: skills,
      );
      
      await addProjectUseCase(project);
      
      // Reload to show the new project
      await _loadData();
    } catch (e) {
      _status = ProjectPartnersStatus.error;
      notifyListeners();
      rethrow;
    }
  }

  Future<void> applyToProject(String listingId, String coverMessage, {String? phoneNumber}) async {
    try {
      await applyToProjectUsecase(listingId, coverMessage, phoneNumber: phoneNumber);
      // Reload data to update application count and user status
      await _loadData();
    } catch (e) {
      rethrow;
    }
  }

  Future<void> loadApplications(String listingId) async {
    isLoadingApplications = true;
    notifyListeners();
    try {
      currentApplications = await getApplicationsUsecase(listingId);
    } catch (e) {
      currentApplications = [];
    } finally {
      isLoadingApplications = false;
      notifyListeners();
    }
  }

  Future<void> updateApplicationStatus(String listingId, String applicationId, String newStatus) async {
    try {
      await updateApplicationStatusUsecase(applicationId, newStatus);
      // Update local state instead of full reload for snappiness
      final index = currentApplications.indexWhere((app) => app.id == applicationId);
      if (index != -1) {
        final oldApp = currentApplications[index];
        currentApplications[index] = ProjectApplicationEntity(
          id: oldApp.id,
          listingId: oldApp.listingId,
          applicantId: oldApp.applicantId,
          applicantName: oldApp.applicantName,
          applicantAvatarUrl: oldApp.applicantAvatarUrl,
          coverMessage: oldApp.coverMessage,
          phoneNumber: oldApp.phoneNumber,
          status: newStatus,
          appliedAgo: oldApp.appliedAgo,
        );
        notifyListeners();
      }
    } catch (e) {
      rethrow;
    }
  }
}
