import 'package:flutter/foundation.dart';
import '../../../../core/constants/app_colors.dart';
import '../../domain/entities/project_application_entity.dart';
import '../../domain/entities/project_partner_entity.dart';
import '../../domain/usecases/add_project_partner_usecase.dart';
import '../../domain/usecases/apply_to_project_usecase.dart';
import '../../domain/usecases/get_applications_usecase.dart';
import '../../domain/usecases/get_project_partners_usecase.dart';
import '../../domain/usecases/update_application_status_usecase.dart';

enum ProjectPartnersStatus { idle, loading, success, error }

class ProjectPartnersProvider extends ChangeNotifier {
  final GetProjectPartnersUsecase getProjectsUsecase;
  final GetFilterChipsUsecase getFilterChipsUsecase;
  final AddProjectPartnerUseCase addProjectUseCase;
  final ApplyToProjectUsecase applyToProjectUsecase;
  final GetApplicationsUsecase getApplicationsUsecase;
  final UpdateApplicationStatusUsecase updateApplicationStatusUsecase;

  ProjectPartnersProvider({
    required this.getProjectsUsecase,
    required this.getFilterChipsUsecase,
    required this.addProjectUseCase,
    required this.applyToProjectUsecase,
    required this.getApplicationsUsecase,
    required this.updateApplicationStatusUsecase,
  }) {
    _loadData();
  }

  List<String> filterChips = [];
  List<ProjectPartnerEntity> allProjects = [];

  ProjectPartnersStatus _status = ProjectPartnersStatus.idle;
  ProjectPartnersStatus get status => _status;
  String? _error;
  String? get error => _error;

  String _selectedFilter = 'All Roles';
  String get selectedFilter => _selectedFilter;

  String _searchQuery = '';
  String get searchQuery => _searchQuery;

  void search(String query) {
    _searchQuery = query;
    notifyListeners();
  }

  // Applications state for the currently viewed project (for creators)
  List<ProjectApplicationEntity> currentApplications = [];
  bool isLoadingApplications = false;

  Future<void> _loadData() async {
    _status = ProjectPartnersStatus.loading;
    notifyListeners();

    try {
      final chipsResult = await getFilterChipsUsecase();
      final projectsResult = await getProjectsUsecase();
      filterChips = chipsResult;
      allProjects = projectsResult;
      _status = ProjectPartnersStatus.success;
      _error = null;
    } catch (e) {
      _error = e.toString();
      _status = ProjectPartnersStatus.error;
    }
    notifyListeners();
  }

  Future<void> reload() => _loadData();

  void setFilter(String filter) {
    _selectedFilter = filter;
    notifyListeners();
  }

  List<ProjectPartnerEntity> get filteredProjects {
    var list = _selectedFilter == 'All Roles'
        ? allProjects
        : allProjects.where((p) => p.skills.any((s) => s.toLowerCase().contains(_selectedFilter.toLowerCase()))).toList();
    if (_searchQuery.isEmpty) return list;
    final q = _searchQuery.toLowerCase();
    return list.where((p) =>
      p.title.toLowerCase().contains(q) ||
      p.description.toLowerCase().contains(q) ||
      p.skills.any((s) => s.toLowerCase().contains(q)),
    ).toList();
  }

  Future<void> addProject(String title, String description, List<String> skills) async {
    _status = ProjectPartnersStatus.loading;
    notifyListeners();

    try {
      final project = ProjectPartnerEntity(
        id: '', // Will be generated by DB
        creatorId: '', // Handled by Supabase
        badge: 'ACADEMIC PROJECT',
        badgeColor: AppColors.toHex(AppColors.badgeAcademicText),
        title: title,
        description: description,
        skills: skills,
      );
      
      await addProjectUseCase(project);
      
      // Reload to show the new project
      await _loadData();
    } catch (e) {
      _status = ProjectPartnersStatus.error;
      notifyListeners();
      rethrow;
    }
  }

  Future<void> applyToProject(String listingId, String coverMessage, {String? phoneNumber}) async {
    try {
      await applyToProjectUsecase(listingId, coverMessage, phoneNumber: phoneNumber);
      // Reload data to update application count and user status
      await _loadData();
    } catch (e) {
      rethrow;
    }
  }

  Future<void> loadApplications(String listingId) async {
    isLoadingApplications = true;
    notifyListeners();
    try {
      currentApplications = await getApplicationsUsecase(listingId);
    } catch (e) {
      currentApplications = [];
    } finally {
      isLoadingApplications = false;
      notifyListeners();
    }
  }

  Future<void> updateApplicationStatus(String listingId, String applicationId, String newStatus) async {
    try {
      await updateApplicationStatusUsecase(applicationId, newStatus);
      // Update local state instead of full reload for snappiness
      final index = currentApplications.indexWhere((app) => app.id == applicationId);
      if (index != -1) {
        final oldApp = currentApplications[index];
        currentApplications[index] = oldApp.copyWith(status: newStatus);
        notifyListeners();
      }
    } catch (e) {
      rethrow;
    }
  }
}
